version: "3"
services:
  php_fpm:
    environment:
      - ENV_DESCRIPTION=default,prod
  varnish:
    depends_on:
      - nginx
      - php_fpm
    ports:
      - "8007:80"
    environment:
      - ENV_DESCRIPTION=default,prod
  npm_build:
    build: containers/npm
    # we don't set as production, as that is for serving node requests, not building stuff.
    #environment:
    #  - NODE_ENV=production
    entrypoint: ["bash", "/var/app/containers/npm/build_prod_assets.sh"]
    volumes:
      - .:/var/app
networks:
  proxy:
    external: true

    entrypoint: ["php", "-d", "memory_limit=-1", "vendor/bin/phpunit"]