version: "3"
services:
  php_fpm:
    environment:
      - ENV_DESCRIPTION=default,prod
  varnish:
    depends_on:
      - nginx
      - php_fpm
    ports:
      - "8007:80"
    environment:
      - ENV_DESCRIPTION=default,prod
  npm_build:
    build: containers/npm
    ports:
      - 8888:8888
    volumes:
      - .:/var/app
    entrypoint: ["bash", "/var/app/containers/npm/compile_sass.sh"]

#    NODE_ENV === 'production'
    
networks:
  proxy:
    external: true